parameters:
    locale: 'hr'
    google_bucket_url: '%env(GOOGLE_BUCKET_URL)%'
    google_client_id: '%env(GOOGLE_CLIENT_ID)%'
    google_client_secret: '%env(GOOGLE_CLIENT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Google\Cloud\Storage\StorageClient:
        factory: ['@App\Service\Google\GoogleStorage', 'getStorageClient']
