framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/async'
                options:
                    consumer: '%env(default::HOSTNAME)%'
                    stream_max_entries: 10000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/failed'
                options:
                    consumer: '%env(default::HOSTNAME)%'
                    stream_max_entries: 10000
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            App\Message\ScrapeItemMessage: async
            App\Message\NewEventImportedMessage: async
