vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute

    mappings:
        events:
            uri_prefix: "%env(GOOGLE_BUCKET_URL)%/images/events"
            upload_destination: events.storage
            namer:
                service: vich_uploader.namer_property
                options: { property: "id" }

        custom_events:
            uri_prefix: "%env(GOOGLE_BUCKET_URL)%/images/custom_events"
            upload_destination: custom_events.storage
            inject_on_load: true
            namer:
                service: vich_uploader.namer_property
                options: { property: "id" }
