; Allow profiling by using GET/POST/COOKIE vars, like done by xdebug extension for chrome/firefox
; Note: For better profiling see provided backfire integration.
xdebug.profiler_enable = 0
xdebug.profiler_output_name = xdebug.out.%t
xdebug.profiler_output_dir = /var/www/var/log
xdebug.profiler_enable_trigger = 1

xdebug.mode=debug
xdebug.client_host=${HOST_IP}
xdebug.start_with_request=yes
xdebug.idekey=${PHP_IDE_KEY}
xdebug.client_port=9003
