imports:
    - { resource: services/google.yaml }

parameters:
    locale: 'hr'
    lastfm_api_key: '%env(LASTFM_API_KEY)%'

when@dev:
    parameters:
        public_upload_dir: '%kernel.project_dir%/public/storage'
        public_read_dir: '/storage'

when@prod:
    parameters:
        public_upload_dir: '%google_bucket_url%'
        public_read_dir: '%google_bucket_url%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            'string $googleClientId': '%google_client_id%'
            'string $googleClientSecret': '%google_client_secret%'
            'string $lastFmApiKey': '%lastfm_api_key%'
            'string $projectDir': '%kernel.project_dir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Scraper\ListScraperInterface:
            tags: ['app.list_scraper']
