imports:
    - { resource: services/google.yaml }

parameters:
    locale: 'hr'

when@dev:
    parameters:
        public_upload_dir: '%kernel.project_dir%/public/storage'
        public_read_dir: '/storage'

when@prod:
    parameters:
        public_upload_dir: '%env(GOOGLE_BUCKET_URL)%'
        public_read_dir: '%env(GOOGLE_BUCKET_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Scraper\ListScraperInterface:
            tags: ['app.list_scraper']

    App\Manager\MediaManager:
        arguments:
            $imagineFilterService: '@liip_imagine.service.filter'
            $projectDir: '%kernel.project_dir%'
