name: CI/CD with Docker Compose

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run docker-compose
              uses: hoverkraft-tech/compose-action@v2.0.1

            - name: Build Docker images
              run: |
                  docker-compose build

            - name: Install dependencies using Composer
              run: |
                  docker-compose run --rm php composer install

            - name: Start services with Docker Compose
              run: |
                  docker-compose up -d

            - name: Run code quality
              run: |
                  docker-compose run --rm php composer analyse-code
