name: CI/CD with Docker Compose

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Composer install
              uses: php-actions/composer@v6
            - name: Php stan
              uses: php-actions/phpstan@v3
              with:
                  path: src/
                  level: 7
