name: CI/CD with Docker Compose

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create env file
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_APP_ENV: ${{ secrets.APP_ENV }}
                  envkey_APP_SECRET: ${{ secrets.APP_SECRET }}
                  envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
                  envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
                  envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                  envkey_PHP_TIMEZONE: ${{ secrets.PHP_TIMEZONE }}
                  envkey_TIMEZONE: ${{ secrets.TIMEZONE }}
                  envkey_HOST_IP: ${{ secrets.HOST_IP }}
                  envkey_PORT_PREFIX: ${{ secrets.PORT_PREFIX }}
                  envkey_GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

            - name: Run docker-compose
              uses: hoverkraft-tech/compose-action@v2.0.1

            - name: Install dependencies using Composer
              run: |
                  docker compose run --rm php composer install

            - name: Run code quality
              run: |
                  docker compose run --rm php composer analyse-code
